//HintName: ISpangle.LusterBits.Tests.TestClass.BasicTypes.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS8600
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603
#pragma warning disable CS8604

using System;

namespace Spangle.LusterBits.Tests.TestClass;

public interface IBasicTypes
{
    public int IntField { get; }

    public long LongField { get; }

    public float FloatField { get; }

    public double DoubleField { get; }

    public bool BoolField { get; }

    public byte ByteField { get; }

    public sbyte SByteField { get; }

    public short ShortField { get; }

    public ushort UShortField { get; }

    public uint UIntField { get; }

    public ulong ULongField { get; }

    public decimal DecimalField { get; }

    public string StringField { get; }

    public string UTF8StringField { get; }

    public string UTF16StringField { get; }

    public string UTF16BigEndianStringField { get; }

}
