//HintName: Spangle.LusterBits.Tests.TestClass.AutoTestStructDeserialized.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS8600
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603
#pragma warning disable CS8604

using System;

namespace Spangle.LusterBits.Tests.TestClass;

/// <summary>
/// Deserialized instance of AutoTestStruct
/// </summary>
public readonly partial struct AutoTestStructDeserialized : IAutoTestStruct
{
    /// <summary>
    /// Zero
    /// </summary>
    public required byte F1Byte { get; init; }

    /// <summary>
    /// Flag1
    /// </summary>
    public required bool F2Bool { get; init; }

    /// <summary>
    /// Flag2
    /// </summary>
    public required bool F3Bool { get; init; }

    /// <summary>
    /// 1 bit field
    /// </summary>
    public required byte F4Byte { get; init; }

    /// <summary>
    /// 13bits ushort over 16bits alignment
    /// </summary>
    public required ushort F5UShort { get; init; }

    /// <summary>
    /// 2bits byte
    /// </summary>
    public required byte F6Byte { get; init; }

    /// <summary>
    /// 2bits byte
    /// </summary>
    public required byte F7Byte { get; init; }

    /// <summary>
    /// 4bits byte
    /// </summary>
    public required byte F8Byte { get; init; }

    public static AutoTestStructDeserialized FromBitFields(AutoTestStruct source)
    {
        return new AutoTestStructDeserialized
        {
            F1Byte = source.F1Byte,
            F2Bool = source.F2Bool,
            F3Bool = source.F3Bool,
            F4Byte = source.F4Byte,
            F5UShort = source.F5UShort,
            F6Byte = source.F6Byte,
            F7Byte = source.F7Byte,
            F8Byte = source.F8Byte,
        };
    }
}
