//HintName: Spangle.LusterBits.Tests.TestClass.BasicTypesDeserialized.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS8600
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603
#pragma warning disable CS8604

using System;

namespace Spangle.LusterBits.Tests.TestClass;

/// <summary>
/// Deserialized instance of BasicTypes
/// </summary>
public readonly partial struct BasicTypesDeserialized : IBasicTypes
{
    public required int IntField { get; init; }

    public required long LongField { get; init; }

    public required float FloatField { get; init; }

    public required double DoubleField { get; init; }

    public required bool BoolField { get; init; }

    public required byte ByteField { get; init; }

    public required sbyte SByteField { get; init; }

    public required short ShortField { get; init; }

    public required ushort UShortField { get; init; }

    public required uint UIntField { get; init; }

    public required ulong ULongField { get; init; }

    public required decimal DecimalField { get; init; }

    public required string StringField { get; init; }

    public required string UTF8StringField { get; init; }

    public required string UTF16StringField { get; init; }

    public required string UTF16BigEndianStringField { get; init; }

    public static BasicTypesDeserialized FromBitFields(BasicTypes source)
    {
        return new BasicTypesDeserialized
        {
            IntField = source.IntField,
            LongField = source.LongField,
            FloatField = source.FloatField,
            DoubleField = source.DoubleField,
            BoolField = source.BoolField,
            ByteField = source.ByteField,
            SByteField = source.SByteField,
            ShortField = source.ShortField,
            UShortField = source.UShortField,
            UIntField = source.UIntField,
            ULongField = source.ULongField,
            DecimalField = source.DecimalField,
            StringField = source.StringField,
            UTF8StringField = source.UTF8StringField,
            UTF16StringField = source.UTF16StringField,
            UTF16BigEndianStringField = source.UTF16BigEndianStringField,
        };
    }
}
