//HintName: ISpangle.LusterBits.Tests.TestClass.AutoTestStruct.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS8600
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603
#pragma warning disable CS8604

using System;

namespace Spangle.LusterBits.Tests.TestClass;

public interface IAutoTestStruct
{
    /// <summary>
    /// Zero
    /// </summary>
    public byte F1Byte { get; }

    /// <summary>
    /// Flag1
    /// </summary>
    public bool F2Bool { get; }

    /// <summary>
    /// Flag2
    /// </summary>
    public bool F3Bool { get; }

    /// <summary>
    /// 1 bit field
    /// </summary>
    public byte F4Byte { get; }

    /// <summary>
    /// 13bits ushort over 16bits alignment
    /// </summary>
    public ushort F5UShort { get; }

    /// <summary>
    /// 2bits byte
    /// </summary>
    public byte F6Byte { get; }

    /// <summary>
    /// 2bits byte
    /// </summary>
    public byte F7Byte { get; }

    /// <summary>
    /// 4bits byte
    /// </summary>
    public byte F8Byte { get; }

}
