//HintName: Spangle.LusterBits.Tests.TestClass.EnumStruct.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS8600
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603
#pragma warning disable CS8604

using System;
using Spangle.LusterBits;

namespace Spangle.LusterBits.Tests.TestClass;

public unsafe partial struct EnumStruct
{
    /// <summary>
    /// Cool Enum Field
    /// </summary>
    public Spangle.LusterBits.Tests.TestClass.SomeEnum EnumField => (Spangle.LusterBits.Tests.TestClass.SomeEnum)(_data[0] >>> 6);

    internal Span<byte> DataAsSpan()
    {
        fixed (byte* ptr = _data)
        {
            return new Span<byte>(ptr, 1);
        }
    }
}
